# Generated by Django 5.1.2 on 2026-07-25

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0036_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaperchange",
            name="logged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_diaper_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Logged by",
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="logged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_feedings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Logged by",
            ),
        ),
    ]
