# Generated by Django 5.1.2 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_diaperchange_logged_by_feeding_logged_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="dosage_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mg", "MG"),
                    ("ml", "mL"),
                    ("tablets", "Tablets"),
                    ("drops", "Drops"),
                ],
                default="",
                max_length=20,
                verbose_name="Dosage Unit",
            ),
        ),
    ]
