# Generated by Django 5.2.15 on 2026-08-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_bath"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bath",
            name="logged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_baths",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Logged by",
            ),
        ),
    ]
